name: Link Issue labels and milestones to PR
description: Github Action to update a pull request with it's corresponding issue's labels and milestones

inputs: 
  owner: 
    description: Repository owner
    required: true
  repo: 
    description: Current repository
    required: true
  myToken: 
    description: Authorization token
    required: true
  pr_number: 
    description: Pull request number
    required: true
runs: 
  using: node16
  main: dist/index.js