name: Test

on: 
  pull_request:
    types: [opened]

jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          owner: ${{ github.repository_owner }}
          myToken: ${{ github.token }}
          repo: ${{ github.event.repository.name }}
          pr_number: ${{ github.event.number }}